# Generated by Django 3.2.8 on 2021-10-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211007_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
